### Import Libraries

In [91]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import PIL.Image
%matplotlib inline

### Load data

In [92]:
df1 = pd.read_csv('train.csv')
df2 = pd.read_csv('test.csv')

In [93]:
df1.head(10)

id                species   margin1   margin2   margin3   margin4  \
0   1            Acer_Opalus  0.007812  0.023438  0.023438  0.003906   
1   2  Pterocarya_Stenoptera  0.005859  0.000000  0.031250  0.015625   
2   3   Quercus_Hartwissiana  0.005859  0.009766  0.019531  0.007812   
3   5        Tilia_Tomentosa  0.000000  0.003906  0.023438  0.005859   
4   6     Quercus_Variabilis  0.005859  0.003906  0.048828  0.009766   
5   8   Magnolia_Salicifolia  0.070312  0.093750  0.033203  0.001953   
6  10    Quercus_Canariensis  0.021484  0.031250  0.017578  0.009766   
7  11          Quercus_Rubra  0.000000  0.000000  0.037109  0.050781   
8  14        Quercus_Brantii  0.005859  0.001953  0.033203  0.015625   
9  15         Salix_Fragilis  0.000000  0.000000  0.009766  0.037109   

    margin5   margin6   margin7  margin8  ...  texture55  texture56  \
0  0.011719  0.009766  0.027344      0.0  ...   0.007812   0.000000   
1  0.025391  0.001953  0.019531      0.0  ...   0.000977   0.000000   
2  0.003906  0.005859  0.068359      0.0  ...   0.154300   0.000000   
3  0.021484  0.019531  0.023438      0.0  ...   0.000000   0.000977   
4  0.013672  0.015625  0.005859      0.0  ...   0.096680   0.000000   
5  0.000000  0.152340  0.007812      0.0  ...   0.145510   0.000000   
6  0.001953  0.042969  0.039062      0.0  ...   0.085938   0.000000   
7  0.003906  0.000000  0.003906      0.0  ...   0.038086   0.025391   
8  0.001953  0.000000  0.023438      0.0  ...   0.000000   0.000000   
9  0.072266  0.000000  0.000000      0.0  ...   0.000000   0.000000   

   texture57  texture58  texture59  texture60  texture61  texture62  \
0   0.002930   0.002930   0.035156    0.00000   0.000000   0.004883   
1   0.000000   0.000977   0.023438    0.00000   0.000000   0.000977   
2   0.005859   0.000977   0.007812    0.00000   0.000000   0.000000   
3   0.000000   0.000000   0.020508    0.00000   0.000000   0.017578   
4   0.021484   0.000000   0.000000    0.00000   0.000000   0.000000   
5   0.041992   0.000000   0.005859    0.00000   0.000000   0.000000   
6   0.040039   0.000000   0.009766    0.00000   0.000000   0.000000   
7   0.009766   0.002930   0.021484    0.00000   0.037109   0.006836   
8   0.008789   0.000000   0.017578    0.00000   0.000000   0.000977   
9   0.000000   0.070312   0.013672    0.19238   0.000000   0.074219   

   texture63  texture64  
0   0.000000   0.025391  
1   0.039062   0.022461  
2   0.020508   0.002930  
3   0.000000   0.047852  
4   0.000000   0.031250  
5   0.001953   0.013672  
6   0.039062   0.003906  
7   0.002930   0.036133  
8   0.033203   0.074219  
9   0.000000   0.000000  

[10 rows x 194 columns]

In [94]:
df2.head()

id   margin1   margin2   margin3   margin4   margin5   margin6   margin7  \
0   4  0.019531  0.009766  0.078125  0.011719  0.003906  0.015625  0.005859   
1   7  0.007812  0.005859  0.064453  0.009766  0.003906  0.013672  0.007812   
2   9  0.000000  0.000000  0.001953  0.021484  0.041016  0.000000  0.023438   
3  12  0.000000  0.000000  0.009766  0.011719  0.017578  0.000000  0.003906   
4  13  0.001953  0.000000  0.015625  0.009766  0.039062  0.000000  0.009766   

   margin8   margin9  ...  texture55  texture56  texture57  texture58  \
0      0.0  0.005859  ...   0.006836   0.000000   0.015625   0.000977   
1      0.0  0.033203  ...   0.000000   0.000000   0.006836   0.001953   
2      0.0  0.011719  ...   0.128910   0.000000   0.000977   0.000000   
3      0.0  0.003906  ...   0.012695   0.015625   0.002930   0.036133   
4      0.0  0.005859  ...   0.000000   0.042969   0.016602   0.010742   

   texture59  texture60  texture61  texture62  texture63  texture64  
0   0.015625        0.0        0.0   0.000000   0.003906   0.053711  
1   0.013672        0.0        0.0   0.000977   0.037109   0.044922  
2   0.000000        0.0        0.0   0.015625   0.000000   0.000000  
3   0.013672        0.0        0.0   0.089844   0.000000   0.008789  
4   0.041016        0.0        0.0   0.007812   0.009766   0.007812  

[5 rows x 193 columns]

In [95]:
df1.shape

(990, 194)

In [96]:
df2.shape

(594, 193)

In [97]:
df1.isnull().any().sum()

0

In [98]:
df2.isnull().any().sum()

0

In [99]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Columns: 194 entries, id to texture64
dtypes: float64(192), int64(1), object(1)
memory usage: 1.5+ MB


In [100]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Columns: 193 entries, id to texture64
dtypes: float64(192), int64(1)
memory usage: 895.7 KB


In [101]:
set((df1.dtypes).to_list())

{dtype('int64'), dtype('float64'), dtype('O')}

In [103]:
df1.describe()

id     margin1     margin2     margin3     margin4  \
count   990.000000  990.000000  990.000000  990.000000  990.000000   
mean    799.595960    0.017412    0.028539    0.031988    0.023280   
std     452.477568    0.019739    0.038855    0.025847    0.028411   
min       1.000000    0.000000    0.000000    0.000000    0.000000   
25%     415.250000    0.001953    0.001953    0.013672    0.005859   
50%     802.500000    0.009766    0.011719    0.025391    0.013672   
75%    1195.500000    0.025391    0.041016    0.044922    0.029297   
max    1584.000000    0.087891    0.205080    0.156250    0.169920   

          margin5     margin6     margin7     margin8     margin9  ...  \
count  990.000000  990.000000  990.000000  990.000000  990.000000  ...   
mean     0.014264    0.038579    0.019202    0.001083    0.007167  ...   
std      0.018390    0.052030    0.017511    0.002743    0.008933  ...   
min      0.000000    0.000000    0.000000    0.000000    0.000000  ...   
25%      0.001953    0.000000    0.005859    0.000000    0.001953  ...   
50%      0.007812    0.015625    0.015625    0.000000    0.005859  ...   
75%      0.017578    0.056153    0.029297    0.000000    0.007812  ...   
max      0.111330    0.310550    0.091797    0.031250    0.076172  ...   

        texture55   texture56   texture57   texture58   texture59   texture60  \
count  990.000000  990.000000  990.000000  990.000000  990.000000  990.000000   
mean     0.036501    0.005024    0.015944    0.011586    0.016108    0.014017   
std      0.063403    0.019321    0.023214    0.025040    0.015335    0.060151   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000977    0.000000    0.004883    0.000000   
50%      0.004883    0.000000    0.005859    0.000977    0.012695    0.000000   
75%      0.043701    0.000000    0.022217    0.009766    0.021484    0.000000   
max      0.429690    0.202150    0.172850    0.200200    0.106450    0.578130   

        texture61   texture62   texture63   texture64  
count  990.000000  990.000000  990.000000  990.000000  
mean     0.002688    0.020291    0.008989    0.019420  
std      0.011415    0.039040    0.013791    0.022768  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000977  
50%      0.000000    0.003906    0.002930    0.011719  
75%      0.000000    0.023438    0.012695    0.029297  
max      0.151370    0.375980    0.086914    0.141600  

[8 rows x 193 columns]

In [104]:
df2.describe()

id     margin1     margin2     margin3     margin4  \
count   594.000000  594.000000  594.000000  594.000000  594.000000   
mean    780.673401    0.017562    0.028425    0.031858    0.022556   
std     465.646977    0.019585    0.038351    0.025719    0.028797   
min       4.000000    0.000000    0.000000    0.000000    0.000000   
25%     368.500000    0.001953    0.001953    0.013672    0.005859   
50%     774.000000    0.009766    0.010743    0.023438    0.013672   
75%    1184.500000    0.028809    0.041016    0.042969    0.027344   
max    1583.000000    0.085938    0.189450    0.167970    0.164060   

          margin5     margin6     margin7     margin8     margin9  ...  \
count  594.000000  594.000000  594.000000  594.000000  594.000000  ...   
mean     0.014527    0.037497    0.019222    0.001085    0.007092  ...   
std      0.018029    0.051372    0.017122    0.002697    0.009515  ...   
min      0.000000    0.000000    0.000000    0.000000    0.000000  ...   
25%      0.001953    0.000000    0.005859    0.000000    0.001953  ...   
50%      0.007812    0.013672    0.015625    0.000000    0.005859  ...   
75%      0.019531    0.056641    0.029297    0.000000    0.007812  ...   
max      0.093750    0.271480    0.087891    0.021484    0.083984  ...   

        texture55   texture56   texture57   texture58   texture59   texture60  \
count  594.000000  594.000000  594.000000  594.000000  594.000000  594.000000   
mean     0.035291    0.005923    0.015033    0.011762    0.015881    0.011217   
std      0.064482    0.026934    0.022318    0.024771    0.014898    0.052530   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000977    0.000000    0.004883    0.000000   
50%      0.003906    0.000000    0.005859    0.001953    0.012695    0.000000   
75%      0.038086    0.000000    0.019531    0.010498    0.022461    0.000000   
max      0.353520    0.441410    0.153320    0.177730    0.083984    0.606450   

        texture61   texture62   texture63   texture64  
count  594.000000  594.000000  594.000000  594.000000  
mean     0.002617    0.019975    0.009389    0.020970  
std      0.011204    0.034704    0.013457    0.023407  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000977  
50%      0.000000    0.003418    0.002930    0.013184  
75%      0.000000    0.022461    0.014648    0.032227  
max      0.123050    0.247070    0.086914    0.149410  

[8 rows x 193 columns]

In [105]:
df1['species'].nunique()

99

### Building Model

In [106]:
test_ids = df2.pop('id')

In [107]:
x = df1.drop('species',axis=1)
y = df1['species']

In [108]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_fit = encoder.fit(df1['species'])
y_label = y_fit.transform(df1['species'])
classes = list(y_fit.classes_)
classes

['Acer_Capillipes',
 'Acer_Circinatum',
 'Acer_Mono',
 'Acer_Opalus',
 'Acer_Palmatum',
 'Acer_Pictum',
 'Acer_Platanoids',
 'Acer_Rubrum',
 'Acer_Rufinerve',
 'Acer_Saccharinum',
 'Alnus_Cordata',
 'Alnus_Maximowiczii',
 'Alnus_Rubra',
 'Alnus_Sieboldiana',
 'Alnus_Viridis',
 'Arundinaria_Simonii',
 'Betula_Austrosinensis',
 'Betula_Pendula',
 'Callicarpa_Bodinieri',
 'Castanea_Sativa',
 'Celtis_Koraiensis',
 'Cercis_Siliquastrum',
 'Cornus_Chinensis',
 'Cornus_Controversa',
 'Cornus_Macrophylla',
 'Cotinus_Coggygria',
 'Crataegus_Monogyna',
 'Cytisus_Battandieri',
 'Eucalyptus_Glaucescens',
 'Eucalyptus_Neglecta',
 'Eucalyptus_Urnigera',
 'Fagus_Sylvatica',
 'Ginkgo_Biloba',
 'Ilex_Aquifolium',
 'Ilex_Cornuta',
 'Liquidambar_Styraciflua',
 'Liriodendron_Tulipifera',
 'Lithocarpus_Cleistocarpus',
 'Lithocarpus_Edulis',
 'Magnolia_Heptapeta',
 'Magnolia_Salicifolia',
 'Morus_Nigra',
 'Olea_Europaea',
 'Phildelphus',
 'Populus_Adenopoda',
 'Populus_Grandidentata',
 'Populus_Nigra',
 'Pr

In [109]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 5)

### Random Forest Classifier

In [120]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 40)
classifier.fit(x_train , y_train)

RandomForestClassifier(n_estimators=40)

In [112]:
pred_train = classifier.predict(x_train)
pred_test = classifier.predict(x_test)

In [113]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_test,pred_test))
print('Training Accuracy: ', accuracy_score(y_train, pred_train))
print('Testing Accuracy: ', accuracy_score(y_test, pred_test))

[[5 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 4 0]
 [0 0 0 ... 0 0 4]]
Training Accuracy:  1.0
Testing Accuracy:  0.9444444444444444


In [126]:
x_test = df2.values

In [127]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_scaled = sc.fit_transform(x)
x_scaled[:5]

array([[-1.76583250e+00, -4.86610735e-01, -1.31357013e-01,
        -3.30955919e-01, -6.82243768e-01, -1.38444190e-01,
        -5.54065671e-01,  4.65218127e-01, -3.95064141e-01,
        -5.84019418e-01,  9.06635731e-01, -4.04138583e-01,
         6.44338462e-01,  5.43065916e-01, -6.07031399e-01,
         9.59250393e-01, -1.05087609e-01,  1.49059268e+00,
        -3.94285572e-01, -8.52978146e-01,  1.26771847e+00,
         2.21416896e-01, -4.15944372e-01, -2.31746723e-01,
         6.20501419e-01, -6.96191053e-01,  1.01826101e+00,
        -5.18691362e-01, -1.32136620e-01,  4.53537867e-02,
        -5.29169249e-02,  5.29321393e-02, -3.00014262e-01,
         3.68271365e-01, -5.18924769e-01, -8.48826290e-01,
        -3.84227342e-01, -5.66484131e-01,  4.28034693e-01,
         1.68214863e+00,  1.11561975e+00, -4.64472846e-01,
        -5.34373975e-01,  1.25474068e-01,  2.52182557e-01,
        -6.94347557e-01,  2.80565955e-01,  9.44087251e-02,
         1.17882028e+00, -5.35978092e-01,  2.04314039e-0

In [128]:
submission = pd.DataFrame(final_predictions, columns=classes)
submission.insert(0, 'id', test_ids)
submission.reset_index()

index    id  Acer_Capillipes  Acer_Circinatum  Acer_Mono  Acer_Opalus  \
0        0     4            0.000            0.000        0.0         0.00   
1        1     7            0.000            0.000        0.0         0.00   
2        2     9            0.025            0.500        0.0         0.00   
3        3    12            0.000            0.000        0.0         0.00   
4        4    13            0.000            0.050        0.0         0.00   
..     ...   ...              ...              ...        ...          ...   
589    589  1576            0.025            0.525        0.0         0.00   
590    590  1577            0.000            0.000        0.0         0.05   
591    591  1579            0.000            0.025        0.0         0.00   
592    592  1580            0.000            0.000        0.0         0.05   
593    593  1583            0.000            0.000        0.0         0.00   

     Acer_Palmatum  Acer_Pictum  Acer_Platanoids  Acer_Rubrum  ...  \
0             0.00        0.050            0.000        0.000  ...   
1             0.00        0.050            0.075        0.025  ...   
2             0.05        0.000            0.000        0.000  ...   
3             0.00        0.000            0.000        0.000  ...   
4             0.00        0.000            0.000        0.000  ...   
..             ...          ...              ...          ...  ...   
589           0.05        0.025            0.000        0.025  ...   
590           0.00        0.000            0.000        0.025  ...   
591           0.00        0.050            0.000        0.000  ...   
592           0.00        0.000            0.025        0.000  ...   
593           0.00        0.025            0.000        0.000  ...   

     Salix_Fragilis  Salix_Intergra  Sorbus_Aria  Tilia_Oliveri  \
0             0.000             0.0        0.000          0.000   
1             0.000             0.0        0.000          0.000   
2             0.025             0.0        0.000          0.025   
3             0.000             0.0        0.000          0.000   
4             0.000             0.0        0.000          0.000   
..              ...             ...          ...            ...   
589           0.025             0.0        0.000          0.000   
590           0.000             0.0        0.025          0.000   
591           0.000             0.0        0.000          0.000   
592           0.000             0.0        0.000          0.025   
593           0.000             0.0        0.000          0.000   

     Tilia_Platyphyllos  Tilia_Tomentosa  Ulmus_Bergmanniana  Viburnum_Tinus  \
0                   0.0            0.000               0.000           0.000   
1                   0.0            0.000               0.000           0.025   
2                   0.0            0.000               0.025           0.000   
3                   0.0            0.025               0.050           0.000   
4                   0.0            0.000               0.050           0.000   
..                  ...              ...                 ...             ...   
589                 0.0            0.000               0.000           0.000   
590                 0.0            0.025               0.000           0.000   
591                 0.0            0.000               0.000           0.000   
592                 0.0            0.025               0.000           0.000   
593                 0.0            0.000               0.000           0.000   

     Viburnum_x_Rhytidophylloides  Zelkova_Serrata  
0                             0.0            0.000  
1                             0.0            0.050  
2                             0.0            0.025  
3                             0.0            0.050  
4                             0.0            0.000  
..                            ...              ...  
589                           0.0            0.000  
590                           0.0    

In [129]:
submission.head(10)

id  Acer_Capillipes  Acer_Circinatum  Acer_Mono  Acer_Opalus  \
0   4            0.000            0.000        0.0        0.000   
1   7            0.000            0.000        0.0        0.000   
2   9            0.025            0.500        0.0        0.000   
3  12            0.000            0.000        0.0        0.000   
4  13            0.000            0.050        0.0        0.000   
5  16            0.025            0.000        0.0        0.075   
6  19            0.000            0.000        0.0        0.525   
7  23            0.000            0.000        0.0        0.000   
8  24            0.000            0.025        0.0        0.025   
9  28            0.075            0.000        0.0        0.000   

   Acer_Palmatum  Acer_Pictum  Acer_Platanoids  Acer_Rubrum  Acer_Rufinerve  \
0           0.00        0.050            0.000        0.000           0.000   
1           0.00        0.050            0.075        0.025           0.000   
2           0.05        0.000            0.000        0.000           0.025   
3           0.00        0.000            0.000        0.000           0.025   
4           0.00        0.000            0.000        0.000           0.150   
5           0.00        0.000            0.000        0.000           0.000   
6           0.00        0.000            0.000        0.000           0.000   
7           0.00        0.050            0.000        0.000           0.000   
8           0.00        0.025            0.000        0.000           0.000   
9           0.00        0.000            0.000        0.000           0.625   

   ...  Salix_Fragilis  Salix_Intergra  Sorbus_Aria  Tilia_Oliveri  \
0  ...           0.000           0.000          0.0          0.000   
1  ...           0.000           0.000          0.0          0.000   
2  ...           0.025           0.000          0.0          0.025   
3  ...           0.000           0.000          0.0          0.000   
4  ...           0.000           0.000          0.0          0.000   
5  ...           0.000           0.000          0.0          0.000   
6  ...           0.000           0.025          0.0          0.000   
7  ...           0.000           0.000          0.0          0.025   
8  ...           0.000           0.025          0.0          0.000   
9  ...           0.000           0.000          0.0          0.000   

   Tilia_Platyphyllos  Tilia_Tomentosa  Ulmus_Bergmanniana  Viburnum_Tinus  \
0                 0.0            0.000               0.000           0.000   
1                 0.0            0.000               0.000           0.025   
2                 0.0            0.000               0.025           0.000   
3                 0.0            0.025               0.050           0.000   
4                 0.0            0.000               0.050           0.000   
5                 0.0            0.025               0.025           0.100   
6                 0.0            0.000               0.025           0.025   
7                 0.0            0.000               0.000           0.025   
8                 0.0            0.025               0.000           0.000   
9                 0.0            0.025               0.025           0.000   

   Viburnum_x_Rhytidophylloides  Zelkova_Serrata  
0                           0.0            0.000  
1                           0.0            0.050  
2                           0.0            0.025  
3                           0.0            0.050  
4                           0.0            0.000  
5                           0.0            0.000  
6                           0.0            0.000  
7                           0.0            0.025  
8                           0.0            0.000  
9                           0.0            0.025  

[10 rows x 100 columns]

In [130]:
submission.to_csv('submission.csv' , index = False)